name: Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0     # Required to retrieve git history of Chromatic

      - name: Cache node modules
        uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn

      - name: Run tests
        run: yarn test

      - name: Check for typescript errors
        run: yarn check-ts-errors

      - name: Run eslint
        run: yarn eslint --quiet

      - name: Run chromatic
        uses: chromaui/action@v1
        with:
          projectToken: 6f3c58ad349c
          token: ${{ secrets.GITHUB_TOKEN }}
          exitZeroOnChanges: true    # don't fail the workflow if snapshots change

  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cedx/setup-dart@v2

      - name: Cache node modules
        uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('**/yarn.lock') }}

      - run: yarn
      - run: yarn build
        env:
          NODE_OPTIONS: --max-old-space-size=4096
      - run: ./node_modules/.bin/serve public &
      - run: pub global activate linkcheck

      - name: Check Links
        run: $HOME/.pub-cache/bin/linkcheck --no-nice :5000
#      - name: Check Links
#        uses: wunderundfitzig/linkcheck-action@v1
#        with:
#          arguments: '--net=host :9000'
